// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihpbzqmzoarbmagenoms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlocGJ6cW16b2FyYm1hZ2Vub21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjc4MTAsImV4cCI6MjA1Njk0MzgxMH0.hnvnIcfjnpdtg0jvak-F3-XpyFxUUOKtcxC_y4aEthU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);